# Generated by Django 5.0.1 on 2024-01-28 18:31

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                default="hello", max_length=128, region=None
            ),
            preserve_default=False,
        ),
    ]
